"""empty message

Revision ID: a98415681a97
Revises: e43ed591b7c5
Create Date: 2020-08-16 12:37:41.107321

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a98415681a97'
down_revision = 'e43ed591b7c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quiz_form',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('modified_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('enabled', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('birthday', sa.DateTime(), nullable=False),
    sa.Column('occupation', sa.String(length=255), nullable=True),
    sa.Column('size', sa.String(length=255), nullable=True),
    sa.Column('fav_brands', sa.String(length=255), nullable=True),
    sa.Column('instagram_handle', sa.String(length=255), nullable=True),
    sa.Column('interest', sa.String(length=255), nullable=True),
    sa.Column('style', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('quiz_form')
    # ### end Alembic commands ###
