"""empty message

Revision ID: b1ee69bde546
Revises: 
Create Date: 2020-08-15 14:35:27.223505

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1ee69bde546'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('birthday', sa.String(length=255), nullable=True))
    op.add_column('user', sa.Column('fav_brands', sa.String(length=255), nullable=True))
    op.add_column('user', sa.Column('instagram_handle', sa.String(length=255), nullable=True))
    op.add_column('user', sa.Column('interest', sa.String(length=255), nullable=True))
    op.add_column('user', sa.Column('occupation', sa.String(length=255), nullable=True))
    op.add_column('user', sa.Column('size', sa.String(length=255), nullable=True))
    op.add_column('user', sa.Column('style', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'style')
    op.drop_column('user', 'size')
    op.drop_column('user', 'occupation')
    op.drop_column('user', 'interest')
    op.drop_column('user', 'instagram_handle')
    op.drop_column('user', 'fav_brands')
    op.drop_column('user', 'birthday')
    # ### end Alembic commands ###
