"""empty message

Revision ID: e43ed591b7c5
Revises: b1ee69bde546
Create Date: 2020-08-16 12:31:01.950453

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e43ed591b7c5'
down_revision = 'b1ee69bde546'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'birthday')
    op.drop_column('user', 'instagram_handle')
    op.drop_column('user', 'style')
    op.drop_column('user', 'size')
    op.drop_column('user', 'fav_brands')
    op.drop_column('user', 'interest')
    op.drop_column('user', 'occupation')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('occupation', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('user', sa.Column('interest', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('user', sa.Column('fav_brands', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('user', sa.Column('size', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('user', sa.Column('style', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('user', sa.Column('instagram_handle', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('user', sa.Column('birthday', mysql.VARCHAR(length=255), nullable=True))
    # ### end Alembic commands ###
